version: '3'
services:
  reverse-proxy: 
    image: traefik:v2.4
<<<<<<< HEAD
    #command: --api.insecure=true --providers.docker # Just needed if we do not have a traefik.yml
=======
#    command: --api.insecure=true --providers.docker
>>>>>>> d4bb0862d7706318a8cfcc26d3f61694ae605d4d
    ports:
      - 80:80
      - 8080:8080 #Management UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
  whoami:
    image: traefik/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
